# Generated by Django 5.1.1 on 2025-07-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_document_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('parsing', 'Parsing PDFs'), ('merging', 'Merging Reports'), ('chunking', 'Chunking Documents'), ('indexing', 'Creating Vector Index'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('use_serialized_tables', models.BooleanField(default=False)),
                ('parent_document_retrieval', models.BooleanField(default=True)),
                ('llm_reranking', models.BooleanField(default=True)),
                ('top_n_retrieval', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='chunk_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='embedding_vector',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='pages_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pictures_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sha1_hash',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='tables_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text_blocks_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='can_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to='djangoapp.role'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'page_number'], name='djangoapp_c_documen_c05301_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['chunk_id'], name='djangoapp_c_chunk_i_6092da_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='djangoapp.documentset'),
        ),
        migrations.AlterField(
            model_name='documentaccess',
            name='document_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='djangoapp.documentset'),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('role', 'document_set')},
        ),
        migrations.AddField(
            model_name='processingpipeline',
            name='document_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='djangoapp.documentset'),
        ),
    ]
