# Generated by Django 4.2.21 on 2025-07-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('parsing', 'Parsing PDFs'), ('merging', 'Merging Reports'), ('chunking', 'Chunking Documents'), ('indexing', 'Creating Vector Index'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('use_serialized_tables', models.BooleanField(default=False)),
                ('parent_document_retrieval', models.BooleanField(default=True)),
                ('llm_reranking', models.BooleanField(default=True)),
                ('top_n_retrieval', models.PositiveIntegerField(default=20)),
                ('document_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='rag.documentset')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='docs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('sha1_hash', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tables_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pictures_count', models.PositiveIntegerField(blank=True, null=True)),
                ('text_blocks_count', models.PositiveIntegerField(blank=True, null=True)),
                ('document_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.documentset')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_vector', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'page_number'], name='rag_chunk_documen_0bad69_idx'), models.Index(fields=['chunk_id'], name='rag_chunk_chunk_i_7be469_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
